### ISSUE TITLE
Options to extract Q network weights?

### ISSUE THREAD

**Issue by Fengdan92** [facebookresearch/ReAgent#144]
Hi,

I was wondering if there is a way to extract the deep Q network weights from the trained predictor.c2? I was thinking I might be able to get the weights by calling predictor.predict_net first, and then extract weights from the net, but I googled around and could not find a way to get the weights.

Thank you,
Fengdan

**Comment by kittipatv** [comment]
We've deprecated caffe2 model export. The pytorch model can be loaded by `torch.load()`.
