### ISSUE TITLE
Cannot build RaspCli inside the cpu Dockerfile

### ISSUE THREAD

**Issue by hsm207** [facebookresearch/ReAgent#177]
I followed the [installation guide](https://github.com/facebookresearch/ReAgent/blob/master/docs/installation.rst#docker) for Docker cpu and can successfully go inside the container and run the tests.

The [tutorial](http://reagent.ai/rasp_tutorial.html#makin-bacon) has a part that says start an RP server. I can't do this because I don't have `./serving/build/RaspCli`.

To build `RaspCli` I ran the following commands inside `./serving/build`:

```bash
wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.3.0%2Bcpu.zip -O libtorch.zip && \
    unzip libtorch.zip && \
    rm libtorch.zip

conda install glog

apt -y install libgflags-dev \
                   libgoogle-glog-dev \
                   libboost-tools-dev \
                   libboost-thread1.62-dev

cmake -DCMAKE_PREFIX_PATH=$HOME/libtorch ..
make
```

The build fails with many `multiple definitions` error. Here is an excerpt:

```
/usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a(morestack.o): In function `__morestack_large_model':
(.text+0x11c): multiple definition of `__morestack_large_model'
/usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a(morestack.o):(.text+0x11c): first defined here
/usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a(morestack.o): In function `__stack_split_initialize':
(.text+0x12c): multiple definition of `__stack_split_initialize'
/usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a(morestack.o):(.text+0x12c): first defined here
/usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a(morestack.o): In function `__morestack_get_guard':
(.text+0x155): multiple definition of `__morestack_get_guard'
/usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a(morestack.o):(.text+0x155): first defined here
/usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a(morestack.o): In function `__morestack_set_guard':
(.text+0x15f): multiple definition of `__morestack_set_guard'
/usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a(morestack.o):(.text+0x15f): first defined here
/usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a(morestack.o): In function `__morestack_make_guard':
(.text+0x169): multiple definition of `__morestack_make_guard'
/usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a(morestack.o):(.text+0x169): first defined here
collect2: error: ld returned 1 exit status
CMakeFiles/RaspCli.dir/build.make:106: recipe for target 'RaspCli' failed
make[2]: *** [RaspCli] Error 1
CMakeFiles/Makefile2:110: recipe for target 'CMakeFiles/RaspCli.dir/all' failed
make[1]: *** [CMakeFiles/RaspCli.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

How can I successfully build ReAgent inside the CPU Docker container?

I am running `Ubuntu 18.04.3 LTS`.

**Comment by thebillkidy** [comment]
Having the same issue here, same Ubuntu set up :)

**Comment by MisterTea** [comment]
I'll take a look, thanks for reporting!

**Comment by thebillkidy** [comment]
Update: Tried fresh Ubuntu install and it's not working either :)

**Comment by MisterTea** [comment]
Fixing in #179

**Comment by hsm207** [comment]
@MisterTea thanks for #179 . The build completes successfully. But it is failing 1 test:


![failed](https://user-images.githubusercontent.com/2398765/67768821-4adfed00-fa8e-11e9-8aa8-1ad944b78e84.png)

**Comment by thebillkidy** [comment]
Build working here as well! :) Thanks!

**Comment by MisterTea** [comment]
@hsm207 That failure is unrelated to RaspCli, please make a separate issue

**Comment by amarchin** [comment]
I have exactly the same setup as well but I still have the same problem. Inside `/serving/build` I can see only the empty folder `bdist.linux-x86_64`.

**Comment by hsm207** [comment]
@amarchin 

Once you have built the docker image, you need to run it.

Then log inside the container cd to the ReAgent folder and do:

```
mkdir serving/build
cd serving/build
cmake -DCMAKE_PREFIX_PATH=$HOME/libtorch ..
make
```

to build RaspCli.

**Comment by amarchin** [comment]
@hsm207 

This what I did but I got this:
```
(base) root@45f9bf1fe824:~/ReAgent/serving/build# cmake -DCMAKE_PREFIX_PATH=$HOME/libtorch ..
CMake Error at CMakeLists.txt:4 (add_subdirectory):
  The source directory

    /home/ReAgent/serving/external/googletest

  does not contain a CMakeLists.txt file
```

**Comment by hsm207** [comment]
@amarchin 

How did you clone your repo?

It should be:

`git clone --recurse-submodules https://github.com/facebookresearch/ReAgent.git`

not:

`git clone https://github.com/facebookresearch/ReAgent.git`

**Comment by amarchin** [comment]
@hsm207 

You're right, thank you. There is an error in the [installation.rst](https://github.com/facebookresearch/ReAgent/blob/master/docs/installation.rst) file in the Docker section then.

**Comment by hsm207** [comment]
@amarchin 
You are welcome.

I've made PR #190 to fix the error in the Docker section.
