### ISSUE TITLE
Possibility of evaluating already fitted policies using the system

### ISSUE THREAD

**Issue by CHARLESYAN1** [facebookresearch/ReAgent#183]
If I have already fitted policies using other RL algorithms which are not currently included in the system, is it possible to add them and do a policy evaluation? If possible, which part should be changed? Thanks

**Comment by czxttkl** [comment]
You can create EvaluationDataPage with data generated by your own RL algorithm. Then call estimators to consume the created EvaluationDataPage. 

See how we create EvaluationDataPage: https://github.com/facebookresearch/ReAgent/blob/1891e876bcf36af69ef4becefde7e93b0fbb0034/ml/rl/workflow/page_handler.py#L91-L99

And how we consume them:   https://github.com/facebookresearch/ReAgent/blob/1891e876bcf36af69ef4becefde7e93b0fbb0034/ml/rl/workflow/page_handler.py#L111
https://github.com/facebookresearch/ReAgent/blob/1891e876bcf36af69ef4becefde7e93b0fbb0034/ml/rl/evaluation/evaluator.py#L117-L128

**Comment by czxttkl** [comment]
We are working towards making evaluation components as a stand-alone library.

**Comment by CHARLESYAN1** [comment]
Thanks a lot
