### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Malik-M** [facebookresearch/ReAgent#186]
I am doing a replication study where I am trying to replicate the "Rainbow: Combining Improvements in Deep Reinforcement Learning" paper. I went though and followed every one of the step listed and ran into a problem when I tried to run
 "python ml/rl/test/workflow/eval_cartpole.py -m outputs/predictor* --softmax_temperature 1" 
this is what I get: 

Traceback (most recent call last):
  File "ml/rl/test/workflow/eval_cartpole.py", line 56, in <module>
    main(args.model, args.softmax_temperature)
  File "ml/rl/test/workflow/eval_cartpole.py", line 21, in main
    model_path = glob.glob(model_path)[0]
IndexError: list index out of range

I am running Ubuntu18.04 LTS with libTorch CUDA 10.1

any help would be highly appreciated

**Comment by czxttkl** [comment]
This means there is no model yet in the path you provided. You'll need to first run some training workflows (e.g., dqn_workflow.py) to generate some models.

**Comment by rezanazari** [comment]
The same error happens to me. Were you able to resolve the issue? It seems that the problem is due to some recent changes, probably it is saving the model with another name instead of "output/predictor*".

**Comment by Malik-M** [comment]
You want to replace “predictor” with the output you got from running the models. You can locate this data if you look in the “output” directory.
