### ISSUE TITLE
No terminal state in timeline format

### ISSUE THREAD

**Issue by rezanazari** [facebookresearch/ReAgent#188]
When doing the training of step 4 using the CartPole-v0, the batch does not have any terminal states and all the transitions appear as non-terminal ones. Seems that the converting the data to timeline format cannot handle this part correctly.

**Comment by MisterTea** [comment]
Interesting, let me take a look

**Comment by MisterTea** [comment]
You are right!  Please try setting the terminal state option to true in this file and then rerunning the timeline: https://github.com/facebookresearch/ReAgent/blob/master/ml/rl/workflow/sample_configs/discrete_action/timeline.json

**Comment by MisterTea** [comment]
@rezanazari What was the conclusion here?  Can you submit a PR with that config change?

**Comment by rezanazari** [comment]
I created a pull request which changes this parameter in timeline.json and now, it creates terminal states.

**Comment by czxttkl** [comment]
I am working on a diff which revisits the usage example and makes sure it works end-to-end.

To achieve that I will change some hyper-parameters and refactor some code.

**Comment by czxttkl** [comment]
> I created a pull request which changes this parameter in timeline.json and now, it creates terminal states.

@rezanazari based on the pull request do you get to train a good policy?

**Comment by rezanazari** [comment]
No, still the policy diverges. I am still not able to train based on the data. I implemented the fitted Q-network method myself and the Q-values remain bounded in my case, but these values become extremely large in ReAgent. I have another issue for this: https://github.com/facebookresearch/ReAgent/issues/189

**Comment by czxttkl** [comment]
I just updated relevant codes (#196 ) and https://reagent.ai/usage.html. If you follow the instructions again, you should be able to learn a policy with 100+ score in Cartpole and TD loss should be well contained.

**Comment by PaulHiemstra** [comment]
@czxttkl my run succeeded nicely this time.
