### ISSUE TITLE
TD loss diverging in DQN workflow

### ISSUE THREAD

**Issue by rezanazari** [facebookresearch/ReAgent#189]
I am running the step 4 of the algorithm using the default parameters, however, I observe that the TD loss in diverging pretty fast. I tested the code both in the local machine and docker, but the same issue happens. My guess is that the target update rate in dqn config is pretty large (it is 0.2 by default). When choosing a smaller value, the training becomes more stable, but I am not 100% sure whether the issue is because of this setting. Could you resolve this issue and update the documentation correspondingly.

**Comment by czxttkl** [comment]
What's the best way to reproduce? Are you just following https://reagent.ai/usage.html#offline-rl-training-batch-rl?

**Comment by rezanazari** [comment]
Yes, I followed the same procedure as explained in the link.

**Comment by rezanazari** [comment]
Here is the result that I get for step 4 training:

INFO:ml.rl.training.loss_reporter:TD LOSS: 4.965
INFO:ml.rl.training.loss_reporter:TD LOSS: 37.244
INFO:ml.rl.training.loss_reporter:TD LOSS: 468.071
INFO:ml.rl.training.loss_reporter:TD LOSS: 2035.612
INFO:ml.rl.training.loss_reporter:TD LOSS: 21475.918
INFO:ml.rl.training.loss_reporter:TD LOSS: 86164.719
INFO:ml.rl.training.loss_reporter:TD LOSS: 363833.531
INFO:ml.rl.training.loss_reporter:TD LOSS: 946168.875
INFO:ml.rl.training.loss_reporter:TD LOSS: 2604999.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 5377271.500
INFO:ml.rl.training.loss_reporter:TD LOSS: 11540389.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 20353164.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 37380560.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 59112612.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 97472632.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 142316864.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 217696560.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 299527808.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 433252096.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 569257664.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 789188928.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 1000393472.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 1343182720.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 1655680256.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 2166121728.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 2607610624.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 3339121408.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 3940104448.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 4955358208.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 5750036480.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 7118372864.000
INFO:ml.rl.training.loss_reporter:TD LOSS: 8143544320.000

**Comment by czxttkl** [comment]
I wouldn't worry too much about td loss divergence in cartpole, as long as you get a working policy that can achieve 190+ reward. Cartpole is such a special environment where the reward is constant across all steps.

**Comment by boaloysius** [comment]
Temporal difference is a measure of q value of the (state, action) pair. I am afraid that, too much divergence indicates that the q values are not stable.

**Comment by rezanazari** [comment]
Large Q-values are not a good sign since it literally shows convergence. My guess is that the divergence is happening because of the issue with the terminal state:
https://github.com/facebookresearch/ReAgent/issues/188

**Comment by rezanazari** [comment]
I added the terminal state and still see the divergence! In my own implementation, the Q-values increase until they become stable at some point. I checked the code in detail but was not able to find any bugs. Is there any way to deactivate the preprocessing?

**Comment by MisterTea** [comment]
@rezanazari Yep, you can manually edit the normalization json file and set the mean to 0 and standard deviation to 1 for all features. This will make normalization do nothing
