### ISSUE TITLE
bad results offline training cartpole

### ISSUE THREAD

**Issue by sdegeusmob** [facebookresearch/ReAgent#192]
I am trying to use offline learning on a dataset, but it returns very bad results.
I saw in another issue that this might be because of the instability and that I should disable the preprocessing. How would I disable this? 
I am using the dqn_workflow for training.

Also I am creating my own datasets by using a model that reaches on average 125 avg rewards and keeping its policy fixed. Would it be able to learn from such a dataset or does offline training need a dataset created by a learning model which would contain multiple policies (starting bad, getting better)?

**Comment by MisterTea** [comment]
1) Preprocessing had a bug where it was mixing the feature values in open source. You should double-check to make sure the features are correct after Preprocessing but IIRC that issue is resolved. 

2) Yes, you need a diverse policy to have successful training. Either add noise to the policy so it doesn't consistently score 125 or use the whole days collection to get diversity.

**Comment by sdegeusmob** [comment]
Also another question, how is the norm file in the discrete_action example generated?
It contains the feature_type "Quantile", but currently I don't see this type available in identify_types.py.

When generating a new norm file it uses the feature_type "Continuous" and this gives bad results on my offline training.


ReAgent⁩ ▸ ⁨ml⁩ ▸ ⁨rl⁩ ▸ ⁨test⁩ ▸ ⁨workflow⁩ ▸ ⁨test_data⁩ ▸ ⁨discrete_action⁩ ▸ cartpole_norm.json:

{"0": "{\"feature_type\": \"QUANTILE\", \"boxcox_lambda\": null, \"boxcox_shift\": null, \"mean\": 0, \"stddev\": 1, \"possible_values\": null, \"quantiles\": [-0.9325759410858154, -0.11454804763197898, -0.06354632377624511, -0.036249015107750894, -0.013861922733485698, 0.008887647651135921, 0.031886988878250117, 0.06421048864722252, 0.11672550588846206, 0.18408811092376712, 0.2652662694454193, 0.3555637866258622, 0.473116099834442, 0.5891120195388797, 0.7273757457733154, 0.868586540222168, 1.016117238998413, 1.1742974281311036, 1.3343838930130008, 1.604723501205444, 2.3982951641082764], \"min_value\": -0.9325759410858154, \"max_value\": 2.3982951641082764}", "1": "{\"feature_type\": \"QUANTILE\", \"boxcox_lambda\": null, \"boxcox_shift\": null, \"mean\": 0, \"stddev\": 1, \"possible_values\": null, \"quantiles\": [-2.8432533740997314, -0.4177091121673584, -0.22203430235385893, -0.17107010185718538, -0.034391749650239944, -0.003721744637005031, 0.022672560065984705, 0.15034710764884945, 0.18193922638893129, 0.20713235735893254, 0.3246956765651703, 0.36443493962287904, 0.39363381862640373, 0.5112518787384033, 0.5511935114860534, 0.5837345719337463, 0.7124261379241943, 0.7630605757236479, 0.9255656242370607, 1.125019884109497, 3.1635074615478516], \"min_value\": -2.8432533740997314, \"max_value\": 3.1635074615478516}", "2": "{\"feature_type\": \"CONTINUOUS\", \"boxcox_lambda\": null, \"boxcox_shift\": null, \"mean\": 0.00898619182407856, \"stddev\": 0.06438369303941727, \"possible_values\": null, \"quantiles\": null, \"min_value\": -0.2092633992433548, \"max_value\": 0.20784969627857208}", "3": "{\"feature_type\": \"CONTINUOUS\", \"boxcox_lambda\": null, \"boxcox_shift\": null, \"mean\": -0.00472704553976655, \"stddev\": 0.33846569061279297, \"possible_values\": null, \"quantiles\": null, \"min_value\": -1.748331904411316, \"max_value\": 2.6361331939697266}"}


new norm file:

{"0": "{\"feature_type\": \"CONTINUOUS\", \"boxcox_lambda\": null, \"boxcox_shift\": null, \"mean\": -0.1368969827890396, \"stddev\": 1.0, \"possible_values\": null, \"quantiles\": null, \"min_value\": -2.3980045318603516, \"max_value\": 2.365572214126587}", "1": "{\"feature_type\": \"CONTINUOUS\", \"boxcox_lambda\": null, \"boxcox_shift\": null, \"mean\": -0.11192971467971802, \"stddev\": 1.0, \"possible_values\": null, \"quantiles\": null, \"min_value\": -2.202932119369507, \"max_value\": 2.2361817359924316}", "2": "{\"feature_type\": \"CONTINUOUS\", \"boxcox_lambda\": null, \"boxcox_shift\": null, \"mean\": -0.004043575841933489, \"stddev\": 1.0, \"possible_values\": null, \"quantiles\": null, \"min_value\": -0.20544876158237457, \"max_value\": 0.20862576365470886}", "3": "{\"feature_type\": \"CONTINUOUS\", \"boxcox_lambda\": null, \"boxcox_shift\": null, \"mean\": 0.008571450598537922, \"stddev\": 1.0, \"possible_values\": null, \"quantiles\": null, \"min_value\": -2.4737002849578857, \"max_value\": 2.7351884841918945}"}

**Comment by sdegeusmob** [comment]
Using a diverse dataset still gives bad results.

Therefor another question, how is the norm file in the discrete_action example generated?
It contains the feature_type "Quantile", but currently I don't see this type available in identify_types.py.

When generating a new norm file on this example dataset it uses the feature_type "Continuous" and does not specify the quantiles. Using this norm file for offline training on the example dataset gives bad results.

ReAgent⁩ ▸ ⁨ml⁩ ▸ ⁨rl⁩ ▸ ⁨test⁩ ▸ ⁨workflow⁩ ▸ ⁨test_data⁩ ▸ ⁨discrete_action⁩ ▸ cartpole_norm.json:

{"0": "{"feature_type": "QUANTILE", "boxcox_lambda": null, "boxcox_shift": null, "mean": 0, "stddev": 1, "possible_values": null, "quantiles": [-0.9325759410858154, -0.11454804763197898, -0.06354632377624511, -0.036249015107750894, -0.013861922733485698, 0.008887647651135921, 0.031886988878250117, 0.06421048864722252, 0.11672550588846206, 0.18408811092376712, 0.2652662694454193, 0.3555637866258622, 0.473116099834442, 0.5891120195388797, 0.7273757457733154, 0.868586540222168, 1.016117238998413, 1.1742974281311036, 1.3343838930130008, 1.604723501205444, 2.3982951641082764], "min_value": -0.9325759410858154, "max_value": 2.3982951641082764}", "1": "{"feature_type": "QUANTILE", "boxcox_lambda": null, "boxcox_shift": null, "mean": 0, "stddev": 1, "possible_values": null, "quantiles": [-2.8432533740997314, -0.4177091121673584, -0.22203430235385893, -0.17107010185718538, -0.034391749650239944, -0.003721744637005031, 0.022672560065984705, 0.15034710764884945, 0.18193922638893129, 0.20713235735893254, 0.3246956765651703, 0.36443493962287904, 0.39363381862640373, 0.5112518787384033, 0.5511935114860534, 0.5837345719337463, 0.7124261379241943, 0.7630605757236479, 0.9255656242370607, 1.125019884109497, 3.1635074615478516], "min_value": -2.8432533740997314, "max_value": 3.1635074615478516}", "2": "{"feature_type": "CONTINUOUS", "boxcox_lambda": null, "boxcox_shift": null, "mean": 0.00898619182407856, "stddev": 0.06438369303941727, "possible_values": null, "quantiles": null, "min_value": -0.2092633992433548, "max_value": 0.20784969627857208}", "3": "{"feature_type": "CONTINUOUS", "boxcox_lambda": null, "boxcox_shift": null, "mean": -0.00472704553976655, "stddev": 0.33846569061279297, "possible_values": null, "quantiles": null, "min_value": -1.748331904411316, "max_value": 2.6361331939697266}"}

new norm file:

{"0": "{"feature_type": "CONTINUOUS", "boxcox_lambda": null, "boxcox_shift": null, "mean": -0.1368969827890396, "stddev": 1.0, "possible_values": null, "quantiles": null, "min_value": -2.3980045318603516, "max_value": 2.365572214126587}", "1": "{"feature_type": "CONTINUOUS", "boxcox_lambda": null, "boxcox_shift": null, "mean": -0.11192971467971802, "stddev": 1.0, "possible_values": null, "quantiles": null, "min_value": -2.202932119369507, "max_value": 2.2361817359924316}", "2": "{"feature_type": "CONTINUOUS", "boxcox_lambda": null, "boxcox_shift": null, "mean": -0.004043575841933489, "stddev": 1.0, "possible_values": null, "quantiles": null, "min_value": -0.20544876158237457, "max_value": 0.20862576365470886}", "3": "{"feature_type": "CONTINUOUS", "boxcox_lambda": null, "boxcox_shift": null, "mean": 0.008571450598537922, "stddev": 1.0, "possible_values": null, "quantiles": null, "min_value": -2.4737002849578857, "max_value": 2.7351884841918945}"}

**Comment by czxttkl** [comment]
After we fixing some bugs and hyperparameters in #196, you should get a decent policy if you follow https://reagent.ai/usage.html#offline-rl-training-batch-rl
