### ISSUE TITLE
Questions about outputs in Tensorboard

### ISSUE THREAD

**Issue by CHARLESYAN1** [facebookresearch/ReAgent#199]
Hi, I have two questions about outputs in tensorbaord. 

1. How do I know whether the model converged or not? 

2. What's the meaning of the last estimate, "value". The graphs are linearly increasing and vary large (10e10). Is that normal? 

Thanks a lot

**Comment by kittipatv** [comment]
1. It depends on the model type. Generally, the loss should be converging to some value.
2. "value" usually means the Q-value. The rate of increase should be decreasing over time. I don't know the exact problem you're solving, but 10e10 seems really large.

**Comment by CHARLESYAN1** [comment]
It turns out some outliers in data are tampering the results. Numbers become normal after additional data cleaning. Thanks~
