### ISSUE TITLE
Why estimators can be negative?

### ISSUE THREAD

**Issue by CHARLESYAN1** [facebookresearch/ReAgent#200]
For the outputted CPE, can WSDR( the weighted sequential doubly robust) estimator be negative? I don't know why but the got some strange negative number. 

Also, which part code actually calculate those estimators? Thanks a lot.

**Comment by kittipatv** [comment]
CPE depends on the quality of reward model. If you got negative values, it's likely that the model predicted negative rewards. The code is here, https://github.com/facebookresearch/ReAgent/blob/master/ml/rl/evaluation/weighted_sequential_doubly_robust_estimator.py

**Comment by CHARLESYAN1** [comment]
Thanks a lot.
