### ISSUE TITLE
Error while executing setup.sh while with docker

### ISSUE THREAD

**Issue by search4mahesh** [facebookresearch/ReAgent#201]
Hi,

I am getting following error while running setup.sh in docker setup.
please suggest.

-- Found Boost: /home/miniconda/lib/cmake/Boost-1.70.0/BoostConfig.cmake (found version "1.70.0") found components: system thread filesystem regex context program_options 
CMake Error at CMakeLists.txt:32 (find_package):
  By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Torch", but
  CMake did not find one.

  Could not find a package configuration file provided by "Torch" with any of
  the following names:

    TorchConfig.cmake
    torch-config.cmake

  Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
  "Torch_DIR" to a directory containing one of the above files.  If "Torch"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/ReAgent/serving/build/CMakeFiles/CMakeOutput.log".
See also "/home/ReAgent/serving/build/CMakeFiles/CMakeError.log"

**Comment by olivier-boisard** [comment]
Hi, I'm having the exact same issue. Git bisect tells me it happens for the first time in commit [fad30d7](https://github.com/facebookresearch/ReAgent/commit/fad30d7aff91f4f9dd17f49d880b0312f0f0c74e). Looks like RASP expect a /home/libtorch folder to be in the docker container, but it's not the case.

I never worked with RASP so far. Would anybody have an issue of what's going on?

**Comment by MisterTea** [comment]
Which docker image are you using?  It looks like the cpu image has libbtorch but not the cuda image.  Working to add them to the cuda image.

**Comment by olivier-boisard** [comment]
I'm using the cuda image, so that could be it :)
