### ISSUE TITLE
Cannot clone submodules due to unadvertised object in exprtk submodule

### ISSUE THREAD

**Issue by PaulHiemstra** [facebookresearch/ReAgent#204]
When I run:

    git clone --recurse-submodules https://github.com/facebookresearch/ReAgent.git

I get:

    error: Server does not allow request for unadvertised object a1b1854ee6206869f0e693929f41469daf7b901c
    Fetched in submodule path 'serving/external/exprtk', but it did not contain a1b1854ee6206869f0e693929f41469daf7b901c. Direct fetching of that commit failed.

I saw that you ran into the same issue in one of the ReAgents tests and [fixed the test](https://github.com/facebookresearch/ReAgent/pull/203). From that I gathered that after the error I can go into the cloned repo and issue:

    git submodule update --force --recursive --init --remote

To fix the issue. 

Is there a more permanent solution coming? If not, maybe you can add the `update --force` trick to the documentation?

**Comment by czxttkl** [comment]
Thanks. This has been fixed in #203

**Comment by ArashPartow** [comment]
Apologies for any inconvenience, as I had to unfortunately perform a force push on the repository.
