### ISSUE TITLE
run multi-step timeline operator

### ISSUE THREAD

**Issue by davidsc-unity3d** [facebookresearch/ReAgent#207]
It seems the rnn world model takes n-step trajectories as opposes to state/next_state SARS records. in the rl preprocessing, it calls the TimeLine operator to produce SARS here 

https://github.com/facebookresearch/ReAgent/blob/b000663598c42a87d000cf18902cb1c18d6a2c86/preprocessing/src/main/scala/com/facebook/spark/rl/Preprocessor.scala#L73

I see the MultiStepTimeline.scala file, it looks like it will produce n-step returns, but it does not seem to be invoked by Preprocesser.scala -- is it ready to use?

**Comment by czxttkl** [comment]
MultiStepTimeline.scala should work. We use it internally at FB. 

We haven't had time to write a Preprocessor dedicated for multi-step preprocessing in the open source world. But I think it just needs some tweak to use ` MultiStepTimeline.run(sqlContext, config)` in `Preprocessor.scala`. 

We have MultiStepTimeline tests in `TimelineTest.scala`, which you can refer.

**Comment by davidsc-unity3d** [comment]
thanks!

**Comment by davidsc-unity3d** [comment]
We modified preprocessor.scala a bit to run the MultiStepTimeline. It builds, but when we run it, we get an error like:

```
cannot resolve 'CAST(sarsa_unshuffled_multi_step.`reward` AS DOUBLE)' due to data type mismatch: cannot cast array<double> to double
```

in looking at the documentation for the operator [output](https://github.com/facebookresearch/ReAgent/blob/master/preprocessing/src/main/scala/com/facebook/spark/rl/MultiStepTimeline.scala#L67) it seems that reward is handled differently than state features. That is for state_features, the output includes the columns

state_features ( MAP<BIGINT,DOUBLE> ). The features of the current step
next_state_features ( ARRAY<MAP<BIGINT,DOUBLE>> ). The features of the subsequent n

however for reward, it will not be divided into current and next, we should just get
reward ( ARRAY<DOUBLE> ). The rewards of consecutive n steps, starting at the current step

is that correct? Is there ReAgent code that depends on this schema - assumes all n step rewad are in one array, but the state_features have current state in state_features, and the next n-1 in an array next_state_features? That's fine if so, just checking

but now I'm staring at this [code](https://github.com/facebookresearch/ReAgent/blob/master/preprocessing/src/main/scala/com/facebook/spark/rl/MultiStepTimeline.scala#L225) trying to figure out if there is a bug there - on the other hand, the tests are passing - so I'm staring at those also :) I'm not a scala programmer so it is taking some time to digest things

@taozhuo

**Comment by davidsc-unity3d** [comment]
I think this was a problem with my lack of experience with hive. I had previously run the Timeline operator - it made a table where reward was a Double, i'm on a GCP dataproc  cluster, so I did what I thought would delete the table - a hadoop fs -rm command, but that must not have deleted the permanent hive table schema. 

After writing output to a different name, it worked, that is my error was because the new array of double was getting jammed into the old schema of a double.

It is something to think about when someone goes to develop an interface to running Timeline or MultistepTimeline - someone might want to experiment with both, should be easy to namespace the output - and/or maybe the operators should remove the existing table if they are there? Before producing output? Or maybe the workflow is as we go day by day, we actually want to add to an existing table? I suspect that at Facebook, one is adding to an existing table, you don't want to delete the old days. Seems like a good workflow, just need to make people aware of it.

**Comment by czxttkl** [comment]
Thanks for reporting! If someone wants to experiment with both single-step and multi-step timeline preprocessing, probably it is best to just specify different output table names. 

Like you said, it would be a useful feature that we can early detect and alert any mismatch between the existing output table schema and expected schema. Going to add this in our wish list.
