### ISSUE TITLE
Example to run SAC doesn't run

### ISSUE THREAD

**Issue by MrCartoonology** [facebookresearch/ReAgent#209]
When I try to run the SAC example

    (reagent) ~/code/ReAgent$ python ml/rl/test/gym/run_gym.py -p ml/rl/test/gym/sac_pendulum_v0.json 

I get an error that something in the json config is not defined in the Dataclass.

    AssertionError: Item in dict missing from <class 'ml.rl.training.sac_trainer.SACTrainerParameters'>: use_value_network
> ~/Code/ReAgent/ml/rl/json_serialize.py(73)from_json()

**Comment by badrinarayan** [comment]
Thank you for bringing it up @MrCartoonology - we have now fixed it. The default config runs for a 1000 episodes, if you want to stop after we reach a score of `-300`, you can also do 

`python ml/rl/test/gym/run_gym.py -p ml/rl/test/gym/sac_pendulum_v0.json -s -300`

This took about 40 episodes to reach with the hyperparams in the provided config.

![image](https://user-images.githubusercontent.com/30771/74888144-02e12080-5332-11ea-93f9-e5d519f46de6.png)
