### ISSUE TITLE
Running ReAgent on Linux/Mac OSX

### ISSUE THREAD

**Issue by venkatesh-narayan** [facebookresearch/ReAgent#286]
Hi,

I was following the installation instructions at https://github.com/facebookresearch/ReAgent/blob/master/docs/installation.rst, and while running "tox" on either Mac or Linux, it has 2-3 failures. I have Python3.7 on both Mac and Linux, and doing running tox after either of pip install "." or pip install ".[gym]" brings the same failures. I also cannot download the Java SDK version 8.0.242.hs-adpt mentioned in the installation guide on either machine. Will this be a problem for running the overall RASP client (https://github.com/facebookresearch/ReAgent/blob/master/docs/rasp_tutorial.rst), and is there a workaround? Thanks!

**Comment by kaiwenw** [comment]
Hi @venkatesh-narayan, we're fixing the failures for tox. 
As for Java,  could you try  java 8.0.252.hs-adpt instead? Let me know if that works, thanks!

**Comment by venkatesh-narayan** [comment]
8.0.252.hs-adpt works
