### ISSUE TITLE
CPE example

### ISSUE THREAD

**Issue by CaralBaby** [facebookresearch/ReAgent#293]
Hi, could you please give an instruction on how to use CPE in dqn_workflow or more examples on CPE? I only found the GridWorld example, which is with discrete state space, but I want to try to use CPE in continuous space. THX. :)
Plus, what is the relationship between CPE and OPE? I am very confused of these two similar files.

**Comment by kaiwenw** [comment]
Hi @CaralBaby thanks for the question! CPE and OPE are equivalent, just different naming. (CPE is counterfactual policy evaluation, OPE is offline policy evaluation). The ope module is actually a second project we're integrating right now into ReAgent. 

For continuous space, do you mean continuous state space or action space? We don't support continuous action spaces right now, unfortunately. 
However for continuous state space, you can look at our DQN Cartpole offline tutorial: https://github.com/facebookresearch/ReAgent/blob/master/docs/usage.rst. Notably, in the config:
    eval_parameters:
      calc_cpe_in_training: true

**Comment by StepanTuchin98** [comment]
Hello, I am trying to include CPE metrics into Tensorboard report as it was done on the Figure 2 in this paper https://arxiv.org/pdf/1811.00260.pdf 

I added parameter, but it didn't help.
      evaluation:
        calc_cpe_in_training: true
I debugged and noticed, that ExtraData metrics field is populated with None value. I am using DiscreteDqn.
Could you please advice me how it should look like? Where should I include some additional configurations or something?

**Comment by CaralBaby** [comment]
Thanks a lot for your answer!
However, it is still confusing for me, that as you said, CPE and OPE are equivalent, why there are two modules for CPE and OPE respectively in the ReAgent project?

**Comment by kaiwenw** [comment]
We're in the middle of transitioning to the new module (named OPE), from the old module (named CPE), so that's why there're two right now. The OPE module should be standalone and decoupled from the Repo as of now.

**Comment by CaralBaby** [comment]
Oh, OK. Thx a lot :)
